/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ProductsChatAgentRouteImport } from './routes/products.chat-agent'
import { Route as ProductsVoiceAgentRouteImport } from './routes/products.voice-agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsChatAgentRoute = ProductsChatAgentRouteImport.update({
  id: '/products/chat-agent',
  path: '/products/chat-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVoiceAgentRoute = ProductsVoiceAgentRouteImport.update({
  id: '/products/voice-agent',
  path: '/products/voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/products/chat-agent': typeof ProductsChatAgentRoute
  '/products/voice-agent': typeof ProductsVoiceAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/products/chat-agent': typeof ProductsChatAgentRoute
  '/products/voice-agent': typeof ProductsVoiceAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/products/chat-agent': typeof ProductsChatAgentRoute
  '/products/voice-agent': typeof ProductsVoiceAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/pricing'
    | '/product'
    | '/products/chat-agent'
    | '/products/voice-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/pricing'
    | '/product'
    | '/products/chat-agent'
    | '/products/voice-agent'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/pricing'
    | '/product'
    | '/products/chat-agent'
    | '/products/voice-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ProductsChatAgentRoute: typeof ProductsChatAgentRoute
  ProductsVoiceAgentRoute: typeof ProductsVoiceAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/chat-agent': {
      id: '/products/chat-agent'
      path: '/products/chat-agent'
      fullPath: '/products/chat-agent'
      preLoaderRoute: typeof ProductsChatAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/voice-agent': {
      id: '/products/voice-agent'
      path: '/products/voice-agent'
      fullPath: '/products/voice-agent'
      preLoaderRoute: typeof ProductsVoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ProductsChatAgentRoute: ProductsChatAgentRoute,
  ProductsVoiceAgentRoute: ProductsVoiceAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
